import type { Metadata } from "next";
import Link from "next/link";
import PublicHeader from "@/components/public-header";
import { publicServices } from "@/lib/public-services";

export const metadata: Metadata = {
  title: "Architect & Structural Engineer in Feni | LAND VIEW Services",
  description: "LAND VIEW Engineers & Architects in Feni provides architectural design, structural design, 3D design, electrical, plumbing, estimating, plan approval, digital survey and soil test services.",
  keywords: ["architect in Feni", "structural engineer Feni", "building design Feni", "engineering consultant Feni", "architectural design Feni", "soil test Feni", "digital survey Feni"],
  alternates: { canonical: "https://landview.com.bd/services" },
  openGraph: { title: "Architect & Engineering Services in Feni | LAND VIEW", description: "Architecture, structural engineering and coordinated building consultancy services from LAND VIEW Engineers & Architects in Feni, Bangladesh.", url: "https://landview.com.bd/services", siteName: "LAND VIEW Engineers & Architects", type: "website" },
  twitter: { card: "summary_large_image", title: "Architect & Engineering Services in Feni | LAND VIEW", description: "Explore LAND VIEW building design and engineering services in Feni, Bangladesh." },
  robots: { index: true, follow: true },
};

const css = `
.lv-services-page{min-height:100vh;background:#07101a;color:#fff}.lv-services-wrap{width:min(100% - 44px,1320px);margin:0 auto}.lv-services-hero{padding:86px 0 56px;border-bottom:1px solid rgba(255,255,255,.1);background:radial-gradient(circle at 75% 20%,rgba(215,154,23,.12),transparent 30%),#07101a}.lv-services-kicker{display:block;margin-bottom:16px;color:#d79a17;font-size:10px;font-weight:900;letter-spacing:.2em}.lv-services-hero h1{max-width:950px;margin:0;font:500 clamp(42px,6vw,76px)/.98 Georgia,"Times New Roman",serif;letter-spacing:-.04em}.lv-services-hero p{max-width:800px;margin:24px 0 0;color:#cfd6dc;font-size:15px;line-height:1.8}.lv-local-proof{padding:28px 0;border-bottom:1px solid rgba(255,255,255,.08);color:#aeb9c2;font-size:12px;line-height:1.8}.lv-local-proof strong{color:#efb733}.lv-service-list{padding:56px 0 48px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.lv-service-card{display:grid;grid-template-columns:auto 1fr auto;gap:18px;align-items:center;padding:26px;border:1px solid rgba(255,255,255,.1);border-radius:14px;background:#0d1721;color:#fff;transition:.2s ease}.lv-service-card:hover{transform:translateY(-3px);border-color:rgba(215,154,23,.65);background:#101d29}.lv-service-card-icon{width:50px;height:50px;display:grid;place-items:center;border:1px solid rgba(215,154,23,.45);border-radius:10px;color:#efb733;font-size:21px}.lv-service-card small{display:block;margin-bottom:6px;color:#8d9aa5;font-size:8px;font-weight:900;letter-spacing:.15em}.lv-service-card h2{margin:0 0 8px;font-size:20px}.lv-service-card p{margin:0;color:#bdc6cd;font-size:12px;line-height:1.7}.lv-service-arrow{color:#d79a17;font-size:20px}.lv-seo-block{margin-bottom:80px;padding:32px;border:1px solid rgba(255,255,255,.1);border-radius:14px;background:#0d1721}.lv-seo-block h2{margin:0 0 15px;font:500 30px/1.1 Georgia,"Times New Roman",serif}.lv-seo-block p{max-width:950px;color:#c5cdd4;font-size:13px;line-height:1.9}.lv-seo-links{display:flex;gap:12px;flex-wrap:wrap;margin-top:20px}.lv-seo-links a{padding:12px 16px;border:1px solid rgba(215,154,23,.55);border-radius:6px;color:#fff;font-size:9px;font-weight:900;text-transform:uppercase;letter-spacing:.05em}@media(max-width:760px){.lv-service-list{grid-template-columns:1fr}.lv-service-card{grid-template-columns:auto 1fr}.lv-service-arrow{display:none}.lv-services-hero{padding-top:60px}}
`;

export default function ServicesPage() {
  const schema = { "@context": "https://schema.org", "@type": "ItemList", name: "LAND VIEW Engineers & Architects Services in Feni", itemListElement: publicServices.map((service, index) => ({ "@type": "ListItem", position: index + 1, name: service.name, url: `https://landview.com.bd/services/${service.slug}` })) };
  const businessSchema = { "@context": "https://schema.org", "@type": "ProfessionalService", "@id": "https://landview.com.bd/#organization", name: "LAND VIEW Engineers & Architects", url: "https://landview.com.bd", email: "landviewcivil@gmail.com", telephone: "+8801408080400", address: { "@type": "PostalAddress", streetAddress: "F. Rahman AC Market (2nd Floor), S.S.K Road", addressLocality: "Feni Sadar", addressRegion: "Feni", postalCode: "3900", addressCountry: "BD" }, areaServed: [{ "@type": "City", name: "Feni" }, { "@type": "Country", name: "Bangladesh" }] };

  return <main className="lv-services-page"><style dangerouslySetInnerHTML={{ __html: css }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(businessSchema) }} /><PublicHeader />
    <section className="lv-services-hero"><div className="lv-services-wrap"><span className="lv-services-kicker">WHAT WE DO · FENI, BANGLADESH</span><h1>Architecture and engineering services in Feni.</h1><p>LAND VIEW Engineers &amp; Architects provides coordinated architectural, structural and technical building consultancy from Feni Sadar. Explore our design, engineering, survey, testing and project-support services below.</p></div></section>
    <div className="lv-services-wrap lv-local-proof"><strong>Local office:</strong> F. Rahman AC Market (2nd Floor), S.S.K Road, Feni Sadar, Feni-3900, Bangladesh. LAND VIEW serves suitable residential, commercial and other building projects in Feni and across Bangladesh.</div>
    <section className="lv-services-wrap lv-service-list" aria-label="LAND VIEW architecture and engineering services in Feni">{publicServices.map((service,index)=><Link href={`/services/${service.slug}`} className="lv-service-card" key={service.slug}><span className="lv-service-card-icon" aria-hidden="true">{service.icon}</span><div><small>FENI SERVICE {String(index+1).padStart(2,"0")}</small><h2>{service.name}</h2><p>{service.shortDescription}</p></div><span className="lv-service-arrow" aria-hidden="true">→</span></Link>)}</section>
    <section className="lv-services-wrap lv-seo-block"><h2>Building design consultancy based in Feni</h2><p>Clients can work with LAND VIEW for architectural planning, structural engineering, 3D visualization and coordinated building services, with supporting services including estimate and costing, plan approval documentation, digital survey and soil-test coordination. Our workflow connects design disciplines so project information can be developed with construction and coordination in mind.</p><div className="lv-seo-links"><Link href="/projects">Explore projects</Link><a href="/#team">Meet the team</a><a href="/#contact">Contact our Feni office</a></div></section>
  </main>;
}
