from pathlib import Path
import re
R=Path.cwd()
def r(path,a,b):
 p=R/path;s=p.read_text();assert a in s,(path,a[:50]);p.write_text(s.replace(a,b,1))
r('lib/role-permissions.ts','  "employees.view", "attendance.view",\n','  "employees.view", "attendance.view", "attendance.edit",\n')
p=R/'components/management-shell-v2.tsx';s=p.read_text()
changes=[
('import { clearStoredSession, landViewApi, readSessionCache, saveSessionCache, type SessionUser } from "@/lib/api";\n','import { clearStoredSession, landViewApi, readSessionCache, saveSessionCache, type SessionUser } from "@/lib/api";\nimport { roleDefaultPermissions } from "@/lib/role-permissions";\n'),
('  { href: "/projectmanagement", label: "Project Management", icon: "◈", permission: "projects.view" },\n  { href: "/admin/estimate", label: "Estimates", icon: "▤", permission: "projects.view" },','  { href: "/projectmanagement", label: "Project Management", icon: "◈", permission: "project_management.view" },\n  { href: "/admin/estimate", label: "Estimates", icon: "▤", permission: "estimates.view" },'),
('  { href: "/admin/finance", label: "Billing", icon: "৳", permission: "finance.view" },\n  { href: "/admin/access", label: "Access Control", icon: "⚿", adminOnly: true },\n  { href: "/admin/accounts/entry", label: "Accounts", icon: "▥", permission: "accounts.view" },\n  { href: "/admin/accounts", label: "Ledger", icon: "≡", permission: "ledger.view" },\n  { href: "/admin/proposals", label: "Proposals", icon: "✎", permission: "proposals.view" },\n  { href: "/admin/website-analytics", label: "Website Analytics", icon: "⌁", adminOnly: true },','  { href: "/admin/finance", label: "Billing", icon: "৳", permission: "finance.view" },\n  { href: "/admin/expenses", label: "Expenses", icon: "◫", permission: "expenses.view_all" },\n  { href: "/admin/accounts/entry", label: "Main Accounts", icon: "▥", adminOnly: true },\n  { href: "/admin/accounts", label: "Ledger", icon: "≡", permission: "ledger.view" },\n  { href: "/admin/proposals", label: "Proposals", icon: "✎", permission: "proposals.view" },\n  { href: "/admin/website-leads", label: "Website Enquiries", icon: "✦", permission: "public.view" },\n  { href: "/admin/website-analytics", label: "Website Analytics", icon: "⌁", permission: "analytics.view" },\n  { href: "/admin/access", label: "Access Control", icon: "⚿", adminOnly: true },'),
('  "/admin/finance", "/admin/accounts/entry", "/admin/accounts",\n  "/admin/employees", "/admin/access", "/admin/website-analytics",','  "/admin/finance", "/admin/expenses", "/admin/accounts/entry", "/admin/accounts",\n  "/admin/employees", "/admin/website-leads", "/admin/website-analytics", "/admin/access",'),
('      if (effectiveRole === "admin" || effectiveRole === "manager") setAccess({ all: true });','      if (effectiveRole === "admin") setAccess({ all: true });\n      else if (effectiveRole === "manager") setAccess({ all: false, permissions: roleDefaultPermissions("manager") });'),
('  const all = Boolean(access?.all || isAdmin || isManager);','  const all = Boolean(access?.all || isAdmin);')]
for a,b in changes: assert a in s,a[:60];s=s.replace(a,b,1)
p.write_text(s)
r('app/admin/layout.tsx','      .primary-nav a[href="/admin/accounts/entry"]{display:none!important}\n','')
r('app/admin/website-analytics/layout.tsx','  await requirePortalSession(["admin"]);','  await requirePortalSession(["admin", "manager"]);')
r('app/admin/expenses/page.tsx',' const canApprove=role==="admin" || latest(perms,userId,"expenses.approve");',' const canApprove=role==="admin" || role==="manager" || latest(perms,userId,"expenses.approve");')
p=R/'app/admin/employees/page.tsx';s=p.read_text();a='''    try {\n      const [employeeRows, userRows] = await Promise.all([\n        landViewApi.getEmployees(),\n        landViewApi.getUsers(),\n      ]);\n      setRows(employeeRows || []);\n      setUsers(userRows || []);\n''';b='''    try {\n      const session = await landViewApi.getSession();\n      const currentRole = String(session?.user?.role || session?.user?.Role || "").trim().toLowerCase();\n      const [employeeRows, userRows] = await Promise.all([\n        landViewApi.getEmployees(),\n        currentRole === "admin" ? landViewApi.getUsers() : Promise.resolve([]),\n      ]);\n      setRows(employeeRows || []);\n      setUsers(userRows || []);\n''';assert a in s;p.write_text(s.replace(a,b,1))
(R/'components/management-role-policy-enforcer.tsx').write_text('''"use client";\nimport { useEffect } from "react";\nimport { usePathname, useRouter } from "next/navigation";\nfunction norm(v:unknown){return String(v??"").trim().toLowerCase()}\nfunction hideButtons(labels:string[]){const w=labels.map(x=>x.toLowerCase());document.querySelectorAll<HTMLButtonElement>("button").forEach(b=>{const t=String(b.textContent||"").trim().toLowerCase();if(w.some(x=>t===x||t.startsWith(x))){b.style.setProperty("display","none","important");b.tabIndex=-1}})}\nexport default function ManagementRolePolicyEnforcer({role:rv}:{role?:string}){const pathname=usePathname(),router=useRouter(),role=norm(rv);useEffect(()=>{if(role!=="manager")return;const blocked=["/admin/access","/admin/accounts/entry","/admin/security","/admin/whatsapp","/admin/website-curation"].some(p=>pathname===p||pathname.startsWith(`${p}/`));if(blocked){router.replace("/admin");return}const apply=()=>{if(pathname==="/admin/accounts"||pathname.startsWith("/admin/accounts/")){document.querySelectorAll<HTMLElement>(".ledger-edit-btn,.ledger-drag-handle,[data-ledger-order-added='true']").forEach(e=>e.style.setProperty("display","none","important"));hideButtons(["Delete","Void","Reorder","Edit"])}if(pathname==="/admin/employees"||pathname.startsWith("/admin/employees/")){document.querySelectorAll<HTMLElement>(".employee-actions").forEach(e=>e.style.setProperty("display","none","important"));hideButtons(["+ Add employee","Add employee","Save employee","Delete","Promote to Manager","Demote to Employee"])}if(pathname==="/admin/municipality-accounts"||pathname.startsWith("/admin/municipality-accounts/"))hideButtons(["Send to Main Ledger","Sending…","Edit"]);if(pathname==="/admin/projects"||pathname.startsWith("/admin/projects/"))hideButtons(["Delete project"]);if(pathname==="/admin/certificates"||pathname.startsWith("/admin/certificates/"))document.querySelectorAll<HTMLElement>(".cert-submit").forEach(e=>e.style.setProperty("display","none","important"))};apply();const o=new MutationObserver(apply);o.observe(document.body,{childList:true,subtree:true});return()=>o.disconnect()},[pathname,role,router]);return null}\n''')
p=R/'app/api/management-dashboard/route.ts';s=p.read_text();a='import { handleLandviewDataAction, selectRows } from "@/lib/supabase-data";\n';assert a in s;s=s.replace(a,a+'import { PERMISSION_DEFINITIONS, mergeRolePermissions, roleDefaultPermissions } from "@/lib/role-permissions";\n',1);s,n=re.subn(r'const PERMISSION_KEYS = \[.*?\] as const;\n','const PERMISSION_KEYS = PERMISSION_DEFINITIONS.map((item) => item.key);\n',s,count=1,flags=re.S);assert n==1
pat=r'async function permissionsFor\(user: Row\) \{.*?\n\}\n\nexport async function GET';repl='''async function permissionsFor(user: Row) {\n  const role = roleOf(user);\n  if (role === "admin") return roleDefaultPermissions("admin");\n  const userKey = userIdOf(user);\n  const overrides: Record<string, boolean> = {};\n  if (userKey) { const rows = await selectRows("app_permissions", { filters: { user_key: userKey }, order: "created_at:asc", limit: 5000 }); for (const row of rows) { const key = text(row.permission); if (key) overrides[key] = text(row.status).toLowerCase() === "active"; } }\n  if (role === "manager" || role === "employee" || role === "client") return mergeRolePermissions(role, overrides);\n  const permissions: Record<string, boolean> = Object.fromEntries(PERMISSION_KEYS.map((key) => [key, false]));\n  if (role === "accounts") for (const key of ACCOUNTS_DEFAULTS) permissions[key] = true;\n  for (const [key, enabled] of Object.entries(overrides)) permissions[key] = enabled; return permissions;\n}\n\nexport async function GET''';s,n=re.subn(pat,repl,s,count=1,flags=re.S);assert n==1;p.write_text(s)
p=R/'app/api/landview/route.ts';s=p.read_text();a='import { supabaseAuthGateway } from "@/lib/supabase-auth";\n';assert a in s;s=s.replace(a,a+'import { mergeRolePermissions, roleDefaultPermissions } from "@/lib/role-permissions";\n',1);pat=r'async function permissionAccess\(user: Row\) \{.*?\n\}\nasync function hasPermission';repl='''async function permissionAccess(user: Row) {\n  const role = roleOf(user), userId = userIdOf(user);\n  if (role === "admin") return { userId, role, all: true, permissions: roleDefaultPermissions("admin") };\n  const rows = userId ? await selectRows("app_permissions", { filters: { user_key: userId }, order: "created_at:asc", limit: 5000 }) : []; const overrides: Record<string, boolean> = {}; for (const row of rows) overrides[text(row.permission)] = text(row.status).toLowerCase() === "active";\n  if (role === "manager" || role === "employee" || role === "client") return { userId, role, all: false, permissions: mergeRolePermissions(role, overrides) };\n  return { userId, role, all: false, permissions: overrides };\n}\nasync function hasPermission''';s,n=re.subn(pat,repl,s,count=1,flags=re.S);assert n==1;p.write_text(s)
p=R/'app/api/project-management/route.ts';s=p.read_text();a='const isAdmin = (u: Row) => roleOf(u) === "admin";\n';assert a in s;s=s.replace(a,a+'const isManagement = (u: Row) => roleOf(u) === "admin" || roleOf(u) === "manager";\n',1);s=s.replace('  if (role !== "admin" && role !== "client") throw new Error("Project Management access is restricted to admin and client accounts.");','  if (role !== "admin" && role !== "manager" && role !== "client") throw new Error("Project Management access is restricted to management and client accounts.");',1);s=s.replace('if (isAdmin(user)) return selectRows("projects",','if (isManagement(user)) return selectRows("projects",',1);s=s.replace('if (!isAdmin(user) && !projectIdsOf(user).includes(code))','if (!isManagement(user) && !projectIdsOf(user).includes(code))',1);s=s.replace('if (!isAdmin(user)) return [];','if (!isManagement(user)) return [];',1);s=s.replace('readOnly: !isAdmin(user)','readOnly: !isManagement(user)');s=s.replace('if (isAdmin(user)) {','if (isManagement(user)) {',1);s=s.replace('(isAdmin(user) ? null : projects[0])','(isManagement(user) ? null : projects[0])',1);a='if (!isAdmin(user)) return fail("Admin permission required.",403);';assert s.count(a)==3;s=s.replace(a,'if (!isManagement(user)) return fail("Management permission required.",403);',2);p.write_text(s)
p=R/'app/api/certificates/route.ts';s=p.read_text();a='import { insertRows, selectRows, updateRows } from "@/lib/supabase-data";\n';assert a in s;s=s.replace(a,a+'import { roleDefaultPermissions } from "@/lib/role-permissions";\n',1);a='async function can(user:Row,permission:string){const role=roleOf(user);if(role==="admin"||role==="manager")return true;';assert a in s;s=s.replace(a,'async function can(user:Row,permission:string){const role=roleOf(user);if(role==="admin")return true;if(role==="manager")return roleDefaultPermissions("manager")[permission]===true;',1);p.write_text(s)
p=R/'lib/supabase-data.ts';s=p.read_text();a='import { getVercelOidcToken } from "@vercel/oidc";\n';assert a in s;s=s.replace(a,a+'import { mergeRolePermissions } from "@/lib/role-permissions";\n',1);marker='function projectLegacy(row: Row, billed?: number) {';assert marker in s;helper='''async function requireWorkspacePermission(user: WorkspaceUser, permission: string) {\n  const role = roleOf(user); if (role === "admin") return; const userKey = text((user as Row)?.userId || (user as Row)?.User_ID || (user as Row)?.username || (user as Row)?.Username); const overrides: Record<string, boolean> = {};\n  if (userKey) { const rows = await selectRows("app_permissions", { filters: { user_key: userKey }, order: "created_at:asc", limit: 5000 }); for (const row of rows) overrides[text(row.permission)] = text(row.status).toLowerCase() === "active"; }\n  const permissions = role === "manager" || role === "employee" || role === "client" ? mergeRolePermissions(role, overrides) : overrides; if (!permissions[permission]) throw new Error(`Permission required: ${permission}`);\n}\nconst ACTION_PERMISSIONS: Record<string, string> = { createProject:"projects.edit", updateProject:"projects.edit", deleteProject:"projects.delete", createEmployee:"employees.manage", updateEmployee:"employees.manage", deleteEmployee:"employees.manage", updateProjectEmployees:"workflow.assign", createDocument:"documents.edit", createSiteVisit:"site.edit", initializeErpSheets:"access.manage" };\n\n''';s=s.replace(marker,helper+marker,1);a='export async function handleLandviewDataAction(action: string, input: Row, user: WorkspaceUser) {\n  const role = roleOf(user);\n';assert a in s;s=s.replace(a,a+'  const requiredPermission = ACTION_PERMISSIONS[action];\n  if (requiredPermission) await requireWorkspacePermission(user, requiredPermission);\n',1);p.write_text(s)
print('patched')
