"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { landViewApi, type FinanceSheetData } from "@/lib/api";

type RequestRow={requestId:string;requesterRole:string;requesterId:string;projectId?:string;employeeId?:string;clientName:string;certificateType:string;category:string;categoryLabel?:string;subject:string;details:string;status:string;certificateId?:string};
type Row=Record<string,any>;
const text=(v:unknown)=>String(v??"").trim();
function pick(row:Row,keys:string[]){for(const k of keys)if(text(row?.[k]))return row[k];return"";}
function records(data:FinanceSheetData){return(data.rows||[]).map(row=>Object.fromEntries((data.headers||[]).map((h,i)=>[text(h),row[i]??""]).filter(([k])=>k)));}
function normProject(v:unknown){const raw=text(v).toUpperCase();const digits=raw.replace(/\D/g,"");return digits?`LV-${Number(digits)}`:raw;}
function statement(category:string){if(category==="structural_design")return"This is to certify that LAND VIEW — Engineers and Architects prepared, reviewed or provided the structural design services stated in this certificate for the referenced project.";if(category==="supervision")return"This is to certify that LAND VIEW — Engineers and Architects provided site supervision services for the referenced project within the scope stated in this certificate.";if(category==="building")return"This is to certify that the building or property described in this certificate has been reviewed or documented by LAND VIEW — Engineers and Architects for the stated purpose.";if(category==="employee")return"This is to certify that the person named in this certificate is or was associated with LAND VIEW — Engineers and Architects in the stated position and capacity.";return"This is to certify that the referenced project has been recorded and served by LAND VIEW — Engineers and Architects in accordance with the scope stated in this certificate.";}

export default function IssueRequestedCertificatePage(){
  const params=useParams<{requestId:string}>();const router=useRouter();const requestId=decodeURIComponent(String(params?.requestId||""));
  const[request,setRequest]=useState<RequestRow|null>(null);const[name,setName]=useState("");const[address,setAddress]=useState("");const[position,setPosition]=useState("");const[subject,setSubject]=useState("");const[description,setDescription]=useState("");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[issued,setIssued]=useState<any>(null);
  useEffect(()=>{let dead=false;(async()=>{try{const r=await fetch("/api/certificate-portal?mode=admin",{cache:"no-store",credentials:"same-origin"});const j=await r.json();if(!r.ok||!j?.success)throw new Error(j?.error||"Could not load request.");const row=(j?.data?.requests||[]).find((x:RequestRow)=>x.requestId===requestId);if(!row)throw new Error("Certificate request not found.");if(dead)return;setRequest(row);setName(row.clientName||row.requesterId||"");setSubject(row.subject||row.categoryLabel||"Certificate");setDescription(row.details||statement(row.category));setPosition((row.requesterRole||"").toLowerCase()==="employee"?"Employee":"Project / Client");
      try{if((row.requesterRole||"").toLowerCase()==="employee"){const employees=await landViewApi.getEmployees();const emp=(employees||[]).find((e:Row)=>text(pick(e,["Employee_ID","Employee ID","EmployeeId"])).toUpperCase()===text(row.employeeId||row.requesterId).toUpperCase());if(emp&&!dead){setName(text(pick(emp,["Employee_Name","Employee Name","Name"]))||row.clientName||row.requesterId);setAddress(text(pick(emp,["Address","Present_Address","Present Address","Location"])));setPosition(text(pick(emp,["Position","Designation","Department"]))||"Employee");}}else{const file=await landViewApi.getFinanceSheet("File List");const id=normProject(row.projectId||row.requesterId);const project=records(file).find((p:Row)=>normProject(pick(p,["FILE ID","File ID","File_ID","Project_ID","Project ID"]))===id);if(project&&!dead){setName(text(pick(project,["Name","Client Name","Client_Name"]))||row.clientName||id);setAddress(text(pick(project,["Address","Location","Project Location","Project_Location"])));}}}catch{}
    }catch(e:any){if(!dead)setError(e?.message||"Could not load request.");}finally{if(!dead)setLoading(false);}})();return()=>{dead=true};},[requestId]);
  async function issue(e:FormEvent){e.preventDefault();if(!request||saving)return;if(!name||!address||!position||!subject){setError("Name, address, position and subject are required.");return;}setSaving(true);setError("");try{const type=(request.category==="building"?"building":request.category==="employee"?"employee":"project");const reference=request.projectId||request.employeeId||request.requesterId;const r=await fetch("/api/certificates",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({type,category:request.category,requestId:request.requestId,name,address,position,subject,reference,description,issuedAt:new Date().toISOString()})});const j=await r.json();if(!r.ok||!j?.success)throw new Error(j?.error||"Could not issue certificate.");setIssued(j.data);}catch(e:any){setError(e?.message||"Could not issue certificate.");}finally{setSaving(false);}}
  if(loading)return <div className="rq-load">Preparing certificate…</div>;
  if(error&&!request)return <div className="rq-load">{error}<br/><Link href="/admin/certificate-requests">Back to requests</Link></div>;
  if(issued)return <div className="rq-page"><section className="rq-success"><small>CERTIFICATE ISSUED</small><h1>{issued.certificateId}</h1><p>The request has been marked Issued automatically. The concerned client or employee can now see this certificate in their portal.</p><div><a href={issued.verificationUrl} target="_blank" rel="noreferrer">VERIFY CERTIFICATE</a><Link href="/admin/certificate-requests">BACK TO REQUESTS</Link><Link href="/admin/certificates">OPEN REGISTRY</Link></div></section><style>{css}</style></div>;
  return <div className="rq-page"><style>{css}</style><header><div><small>APPROVED CERTIFICATE REQUEST</small><h1>Issue certificate.</h1><p>Request {request?.requestId} · {request?.categoryLabel||request?.category}</p></div><Link href="/admin/certificate-requests">BACK TO REQUESTS</Link></header>{error&&<div className="rq-error">{error}</div>}<form onSubmit={issue}><div className="rq-summary"><span>REQUESTER</span><strong>{request?.clientName||request?.requesterId}</strong><p>{request?.projectId||request?.employeeId||request?.requesterId} · {request?.subject}</p></div><div className="rq-grid"><label><span>NAME / CLIENT / EMPLOYEE</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label><span>POSITION / DESIGNATION</span><input value={position} onChange={e=>setPosition(e.target.value)}/></label><label className="full"><span>ADDRESS</span><input value={address} onChange={e=>setAddress(e.target.value)}/></label><label className="full"><span>CERTIFICATE SUBJECT</span><input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label className="full"><span>CERTIFICATE STATEMENT</span><textarea value={description||statement(request?.category||"")} onChange={e=>setDescription(e.target.value)}/></label></div><button disabled={saving}>{saving?"ISSUING…":"ISSUE CERTIFICATE & CREATE QR"}</button></form></div>;
}

const css=`.rq-page{display:grid;gap:18px;color:#eee}.rq-page header{display:flex;justify-content:space-between;align-items:end;gap:20px}.rq-page header small,.rq-success small{color:#ef6e64;font-size:8px;font-weight:900;letter-spacing:.13em}.rq-page h1{font-size:32px;margin:7px 0 4px}.rq-page p{color:#858b91;font-size:10px}.rq-page header a,.rq-success a{height:40px;padding:0 13px;border:1px solid #3b3f43;border-radius:8px;color:#ddd;text-decoration:none;display:inline-flex;align-items:center;font-size:8px;font-weight:900}.rq-page form,.rq-success{border:1px solid #34373b;background:#1b1d1f;border-radius:12px;padding:20px}.rq-summary{padding:14px;border:1px solid #34383c;background:#151719;border-radius:9px;margin-bottom:16px}.rq-summary span,.rq-grid span{display:block;color:#81888e;font-size:8px;font-weight:900;margin-bottom:6px}.rq-summary strong{font-size:15px}.rq-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.rq-grid label{display:grid}.rq-grid .full{grid-column:1/-1}.rq-grid input,.rq-grid textarea{border:1px solid #3a3f44;background:#101214;color:#eee;border-radius:8px;padding:0 11px}.rq-grid input{height:43px}.rq-grid textarea{min-height:120px;padding-top:10px}.rq-page form>button{width:100%;height:48px;border:0;border-radius:8px;background:#ef493b;color:#fff;font-size:9px;font-weight:900;margin-top:16px;cursor:pointer}.rq-page form>button:disabled{opacity:.55}.rq-error{padding:11px;border:1px solid #66332d;background:#321c19;color:#f2aaa2;border-radius:8px;font-size:10px}.rq-success{text-align:center;padding:42px 24px}.rq-success h1{font-size:27px}.rq-success>div{display:flex;justify-content:center;gap:8px;flex-wrap:wrap;margin-top:20px}.rq-load{padding:30px;color:#ccc}.rq-load a{color:#ef6e64}@media(max-width:650px){.rq-page header,.rq-grid{display:grid}.rq-grid{grid-template-columns:1fr}.rq-grid .full{grid-column:auto}}`;
