"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { landViewApi } from "@/lib/api";

type Row=Record<string,any>;
const categories=["Office Supplies","Transport","Food & Refreshment","Utility","Printing","Site Travel","Repair & Maintenance","Software / Subscription","Miscellaneous"];
function t(v:any){return String(v??"").trim()}
function money(v:any){const n=Number(String(v??0).replace(/,/g,""));return Number.isFinite(n)?`৳${n.toLocaleString("en-BD")}`:"৳0"}

export default function EmployeeExpenseCenter(){
 const [rows,setRows]=useState<Row[]>([]),[user,setUser]=useState<any>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 const [form,setForm]=useState({date:new Date().toISOString().slice(0,10),category:categories[0],description:"",amount:"",method:"Cash",project:"",reference:"",notes:""});
 async function load(){setLoading(true);setError("");try{const [e,s]=await Promise.all([landViewApi.getErpRecords("expenses"),landViewApi.getSession()]);setRows(e||[]);setUser(s?.user||null)}catch(e:any){setError(e?.message||"Could not load expenses.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const employeeId=t(user?.employeeId||user?.Employee_ID||user?.userId||user?.User_ID);
 const mine=useMemo(()=>rows.filter(r=>t(r.Created_By||r.Employee_ID)===employeeId),[rows,employeeId]);
 async function submit(e:FormEvent){e.preventDefault();if(!form.description.trim()||Number(form.amount)<=0){setError("Enter a description and a valid amount.");return}setSaving(true);setError("");setOk("");try{await landViewApi.createErpRecord("expenses",{Expense_Date:form.date,Category:form.category,Description:form.description.trim(),Amount:Number(form.amount),Payment_Method:form.method,Project_ID:form.project.trim().toUpperCase(),Reference:form.reference.trim(),Status:"Pending",Notes:form.notes.trim(),Created_At:new Date().toISOString(),Created_By:employeeId});setOk("Expense submitted for approval.");setForm(v=>({...v,description:"",amount:"",project:"",reference:"",notes:""}));await load()}catch(e:any){setError(e?.message||"Could not submit expense.")}finally{setSaving(false)}}
 return <section className="eec" id="expenses"><style>{`
 .eec{margin-top:22px;padding:20px;border:1px solid #3b3b3b;border-radius:12px;background:#1c1c1c;color:#f4f4f4}.eec-head{display:flex;justify-content:space-between;gap:16px;align-items:end}.eec-head h2{margin:4px 0 0}.eec-head p{max-width:520px;color:#aaa;font-size:11px;line-height:1.5}.eec-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:18px}.eec-form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.eec-form label{display:grid;gap:6px;font-size:9px;color:#aaa}.eec-form label.wide{grid-column:1/-1}.eec input,.eec select,.eec textarea{width:100%;border:1px solid #414141;border-radius:7px;background:#111;color:#eee;padding:10px;font-size:11px}.eec textarea{min-height:76px;resize:vertical}.eec-submit{grid-column:1/-1;height:42px;border:0;border-radius:7px;background:#ef493b;color:#fff;font-weight:800;font-size:10px;cursor:pointer}.eec-submit:disabled{opacity:.5}.eec-msg{grid-column:1/-1;padding:9px 10px;border-radius:7px;font-size:10px}.eec-msg.err{background:#431e20;color:#ff9c9c}.eec-msg.ok{background:#173723;color:#99e5af}.eec-list{display:grid;gap:8px;align-content:start}.eec-row{padding:11px 12px;border:1px solid #3b3b3b;border-radius:8px;background:#252525;display:grid;grid-template-columns:1fr auto;gap:10px}.eec-row strong,.eec-row small{display:block}.eec-row small{margin-top:4px;color:#999;font-size:9px}.eec-status{font-size:9px;padding:4px 7px;border-radius:999px;background:#393939;height:max-content}.eec-status.pending{background:#4c3a1e;color:#ffd67c}.eec-status.approved{background:#173c28;color:#8ee0ab}.eec-status.rejected{background:#472124;color:#ff9d9d}@media(max-width:850px){.eec-grid{grid-template-columns:1fr}}@media(max-width:560px){.eec-form{grid-template-columns:1fr}.eec-form label.wide,.eec-submit{grid-column:auto}}
 `}</style><div className="eec-head"><div><small>OFFICE EXPENSES</small><h2>Submit day-to-day expense</h2></div><p>Use this for LAND VIEW office expenses, not client billing. New submissions remain Pending until an authorized approver decides them.</p></div><div className="eec-grid"><form className="eec-form" onSubmit={submit}>{error&&<div className="eec-msg err">{error}</div>}{ok&&<div className="eec-msg ok">{ok}</div>}<label>Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="wide">Description<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="What was the expense for?"/></label><label>Amount (BDT)<input inputMode="decimal" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value.replace(/[^0-9.]/g,"")})} placeholder="0"/></label><label>Payment method<select value={form.method} onChange={e=>setForm({...form,method:e.target.value})}><option>Cash</option><option>bKash</option><option>Bank</option><option>Card</option><option>Other</option></select></label><label>Project ID (optional)<input value={form.project} onChange={e=>setForm({...form,project:e.target.value})} placeholder="LV-133"/></label><label>Reference (optional)<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} placeholder="Receipt / trx ID"/></label><label className="wide">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="eec-submit" disabled={saving}>{saving?"SUBMITTING…":"SUBMIT FOR APPROVAL"}</button></form><div className="eec-list"><strong>My recent submissions</strong>{loading?<small>Loading…</small>:[...mine].reverse().slice(0,8).map((r,i)=>{const s=t(r.Status)||"Pending";return <div className="eec-row" key={t(r.Expense_ID)||i}><div><strong>{t(r.Description)||t(r.Category)||"Expense"} · {money(r.Amount)}</strong><small>{t(r.Expense_Date)||"—"} · {t(r.Category)||"General"}</small></div><span className={`eec-status ${s.toLowerCase()}`}>{s}</span></div>})}{!loading&&!mine.length&&<small>No expense submissions yet.</small>}</div></div></section>
}