"use client";

import { FormEvent, useEffect, useState } from "react";
import { landViewApi } from "@/lib/api";

const categories=["Office Supplies","Transport","Food & Refreshment","Utility","Printing","Site Travel","Repair & Maintenance","Software / Subscription","Miscellaneous"];
function t(v:any){return String(v??"").trim()}

export default function EmployeeExpenseCenter(){
 const [user,setUser]=useState<any>(null),[saving,setSaving]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 const [form,setForm]=useState({date:new Date().toISOString().slice(0,10),category:categories[0],description:"",amount:"",method:"Cash",project:"",reference:"",notes:""});
 useEffect(()=>{void landViewApi.getSession().then(s=>setUser(s?.user||null)).catch(()=>setError("Could not verify your employee session."))},[]);
 const employeeId=t(user?.employeeId||user?.Employee_ID||user?.userId||user?.User_ID);
 async function submit(e:FormEvent){e.preventDefault();if(!employeeId){setError("Employee identity is unavailable. Sign in again.");return}if(!form.description.trim()||Number(form.amount)<=0){setError("Enter a description and a valid amount.");return}setSaving(true);setError("");setOk("");try{await landViewApi.createErpRecord("expenses",{Expense_Date:form.date,Category:form.category,Description:form.description.trim(),Amount:Number(form.amount),Payment_Method:form.method,Project_ID:form.project.trim().toUpperCase(),Reference:form.reference.trim(),Status:"Pending",Notes:form.notes.trim(),Created_At:new Date().toISOString(),Created_By:employeeId,Employee_ID:employeeId});setOk("Expense submitted for approval.");setForm(v=>({...v,description:"",amount:"",project:"",reference:"",notes:""}));}catch(e:any){setError(e?.message||"Could not submit expense.")}finally{setSaving(false)}}
 return <section className="eec" id="expenses"><style>{`
 .eec{margin-top:22px;padding:20px;border:1px solid #3b3b3b;border-radius:12px;background:#1c1c1c;color:#f4f4f4}.eec-head{display:flex;justify-content:space-between;gap:16px;align-items:end}.eec-head h2{margin:4px 0 0}.eec-head p{max-width:520px;color:#aaa;font-size:11px;line-height:1.5}.eec-grid{display:grid;grid-template-columns:1fr .8fr;gap:18px;margin-top:18px}.eec-form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.eec-form label{display:grid;gap:6px;font-size:9px;color:#aaa}.eec-form label.wide{grid-column:1/-1}.eec input,.eec select,.eec textarea{width:100%;border:1px solid #414141;border-radius:7px;background:#111;color:#eee;padding:10px;font-size:11px}.eec textarea{min-height:76px;resize:vertical}.eec-submit{grid-column:1/-1;height:42px;border:0;border-radius:7px;background:#ef493b;color:#fff;font-weight:800;font-size:10px;cursor:pointer}.eec-submit:disabled{opacity:.5}.eec-msg{grid-column:1/-1;padding:9px 10px;border-radius:7px;font-size:10px}.eec-msg.err{background:#431e20;color:#ff9c9c}.eec-msg.ok{background:#173723;color:#99e5af}.eec-info{padding:16px;border:1px solid #393939;border-radius:9px;background:#242424}.eec-info strong{display:block;margin-bottom:8px}.eec-info p{margin:0;color:#9fa4a8;font-size:10px;line-height:1.6}.eec-info ul{margin:12px 0 0;padding-left:18px;color:#c2c6c9;font-size:10px;line-height:1.8}@media(max-width:850px){.eec-grid{grid-template-columns:1fr}}@media(max-width:560px){.eec-form{grid-template-columns:1fr}.eec-form label.wide,.eec-submit{grid-column:auto}}
 `}</style><div className="eec-head"><div><small>OFFICE EXPENSES</small><h2>Submit day-to-day expense</h2></div><p>Use this for LAND VIEW office expenses, not client billing. New submissions remain Pending until an authorized approver decides them.</p></div><div className="eec-grid"><form className="eec-form" onSubmit={submit}>{error&&<div className="eec-msg err">{error}</div>}{ok&&<div className="eec-msg ok">{ok}</div>}<label>Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="wide">Description<input value={form.description} onChange={e=>{setForm({...form,description:e.target.value});setError("")}} placeholder="What was the expense for?"/></label><label>Amount (BDT)<input inputMode="decimal" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value.replace(/[^0-9.]/g,"")})} placeholder="0"/></label><label>Payment method<select value={form.method} onChange={e=>setForm({...form,method:e.target.value})}><option>Cash</option><option>bKash</option><option>Bank</option><option>Card</option><option>Other</option></select></label><label>Project ID (optional)<input value={form.project} onChange={e=>setForm({...form,project:e.target.value})} placeholder="LV-133"/></label><label>Reference (optional)<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} placeholder="Receipt / trx ID"/></label><label className="wide">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="eec-submit" disabled={saving||!employeeId}>{saving?"SUBMITTING…":"SUBMIT FOR APPROVAL"}</button></form><aside className="eec-info"><strong>Approval flow</strong><p>Your submission is saved as Pending. Only authorized management should approve, reject or return it for correction.</p><ul><li>Keep client billing separate.</li><li>Add a receipt/reference when available.</li><li>Use Project ID only when the expense belongs to a project.</li><li>Company-wide expense history is not downloaded into the employee portal.</li></ul></aside></div></section>
}