"use client";

import { useEffect, useMemo, useState } from "react";

type AuditEntry={id:string;certificateId:string;action:string;actor:string;actorName:string;details:Record<string,unknown>;createdAt:string};

export default function CertificateAuditPage(){
  const [entries,setEntries]=useState<AuditEntry[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [query,setQuery]=useState("");const [action,setAction]=useState("all");const [date,setDate]=useState("");
  async function load(){setLoading(true);setError("");try{const r=await fetch("/api/certificates/audit",{cache:"no-store",credentials:"same-origin"});const j=await r.json();if(!r.ok||!j?.success)throw new Error(j?.error||"Could not load audit history.");setEntries(Array.isArray(j?.data?.entries)?j.data.entries:[]);}catch(e:any){setError(e?.message||"Could not load audit history.");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  const actions=useMemo(()=>Array.from(new Set(entries.map(e=>e.action).filter(Boolean))).sort(),[entries]);
  const filtered=useMemo(()=>entries.filter(e=>{const q=query.trim().toLowerCase();const text=[e.certificateId,e.action,e.actorName,e.actor,JSON.stringify(e.details||{})].join(" ").toLowerCase();const day=e.createdAt?new Date(e.createdAt).toLocaleDateString("en-CA",{timeZone:"Asia/Dhaka"}):"";return(!q||text.includes(q))&&(action==="all"||e.action===action)&&(!date||day===date);}),[entries,query,action,date]);
  return <main style={shell}>
    <header style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start",marginBottom:16}}><div><h1 style={{margin:0,fontSize:27}}>Certificate Audit History</h1><p style={muted}>Permanent history of certificate issuance, reissues, revocations, withdrawals and template changes.</p></div><button onClick={load} style={button}>Refresh</button></header>
    {error&&<div style={errorBox}>{error}</div>}
    <section style={card}>
      <div style={filters}><input style={input} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search certificate, person, action or details…"/><select style={input} value={action} onChange={e=>setAction(e.target.value)}><option value="all">All actions</option>{actions.map(a=><option value={a} key={a}>{human(a)}</option>)}</select><input style={input} type="date" value={date} onChange={e=>setDate(e.target.value)}/></div>
      <div style={{fontSize:12,color:"#667085",margin:"0 0 10px"}}>{filtered.length} of {entries.length} audit entries</div>
      <div style={tableWrap}>{loading?<div style={empty}>Loading audit history…</div>:filtered.length===0?<div style={empty}>No audit entries match these filters.</div>:<table style={table}><thead><tr><th style={th}>Date & Time</th><th style={th}>Certificate / Template</th><th style={th}>Action</th><th style={th}>Performed By</th><th style={th}>Details</th></tr></thead><tbody>{filtered.map((e,i)=><tr key={e.id||`${e.certificateId}-${e.createdAt}-${i}`}><td style={td}>{formatDate(e.createdAt)}</td><td style={td}><strong>{e.certificateId||"—"}</strong></td><td style={td}><span style={status}>{human(e.action)}</span></td><td style={td}><strong>{e.actorName||"System"}</strong>{e.actor&&e.actor!==e.actorName&&<small style={small}>{e.actor}</small>}</td><td style={td}>{details(e.details)}</td></tr>)}</tbody></table>}</div>
    </section>
  </main>;
}

function human(value:string){return String(value||"—").replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());}
function formatDate(value:string){if(!value)return"—";const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString("en-GB",{timeZone:"Asia/Dhaka",day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"});}
function details(value:Record<string,unknown>){const entries=Object.entries(value||{}).filter(([,v])=>v!==null&&v!==undefined&&v!=="");if(!entries.length)return <span style={muted}>—</span>;return <div>{entries.slice(0,6).map(([k,v])=><div key={k} style={{fontSize:11,lineHeight:1.45}}><b>{human(k)}:</b> {typeof v==="object"?JSON.stringify(v):String(v)}</div>)}</div>}
const shell={maxWidth:1450,margin:"0 auto",padding:"22px"} as const;const card={background:"#fff",border:"1px solid #e4e7ec",borderRadius:14,padding:18,boxShadow:"0 3px 12px #1018280c"} as const;const muted={fontSize:12,color:"#667085"} as const;const filters={display:"grid",gridTemplateColumns:"minmax(280px,1fr) 220px 180px",gap:10,marginBottom:10} as const;const input={boxSizing:"border-box" as const,width:"100%",border:"1px solid #d0d5dd",borderRadius:9,padding:"9px 10px",background:"#fff",color:"#101828",font:"inherit"};const button={border:"1px solid #d0d5dd",background:"#fff",borderRadius:9,padding:"9px 13px",fontWeight:800,cursor:"pointer"};const tableWrap={overflow:"auto",border:"1px solid #e4e7ec",borderRadius:11} as const;const table={width:"100%",borderCollapse:"collapse" as const,minWidth:1000};const th={padding:"10px 12px",textAlign:"left" as const,borderBottom:"1px solid #eaecf0",background:"#f9fafb",fontSize:10.5,textTransform:"uppercase" as const,letterSpacing:.4,color:"#475467"};const td={padding:"11px 12px",textAlign:"left" as const,borderBottom:"1px solid #eaecf0",fontSize:12,verticalAlign:"top" as const};const status={display:"inline-flex",background:"#f2f4f7",color:"#344054",borderRadius:999,padding:"4px 8px",fontSize:10,fontWeight:900};const small={display:"block",fontSize:10,color:"#98a2b3",marginTop:2};const empty={padding:30,textAlign:"center" as const,color:"#667085"};const errorBox={background:"#fef3f2",color:"#b42318",padding:"10px 12px",borderRadius:9,marginBottom:12,fontSize:13};
