"use client";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { landViewApi, ProjectServiceFolderInfo } from "@/lib/api";
import { ErrorState, Field, LoadingState, Money, PageHeader, StatusBadge, formatDate, pick } from "@/components/lv-ui";
import { PROJECT_SERVICE_FOLDERS, uploadProjectFile } from "@/lib/project-service-folders";

const folderCss=`
.service-folder-panel{margin-top:18px}
.service-folder-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}
.service-folder-card{min-width:0;overflow:hidden;padding:0!important;border:1px solid rgba(255,255,255,.1)!important;border-radius:12px!important;background:linear-gradient(145deg,rgba(255,255,255,.035),rgba(255,255,255,.015))!important}
.service-folder-head{display:flex;align-items:center;gap:11px;padding:14px 15px;border-bottom:1px solid rgba(255,255,255,.07)}
.service-folder-number{display:grid;place-items:center;flex:0 0 auto;width:28px;height:28px;border:1px solid rgba(214,166,44,.3);border-radius:7px;background:rgba(214,166,44,.06);color:#d6a62c;font-size:9px;font-weight:800}
.service-folder-name{min-width:0;flex:1;color:#f3f6f7;font-size:12px;font-weight:700}
.service-folder-open{flex:0 0 auto;padding:7px 9px;border:1px solid rgba(255,255,255,.1);border-radius:7px;color:#aab5bc!important;font-size:8px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;transition:.18s ease}
.service-folder-open:hover{border-color:rgba(214,166,44,.4);color:#d6a62c!important}
.service-upload-body{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;padding:13px 15px}
.service-file-picker{min-width:0;display:flex;align-items:center;gap:10px;padding:10px 11px;border:1px dashed rgba(255,255,255,.14);border-radius:8px;background:rgba(3,12,19,.35);cursor:pointer;transition:.18s ease}
.service-file-picker:hover{border-color:rgba(214,166,44,.45)}
.service-file-picker input{position:absolute;width:1px;height:1px;opacity:0;pointer-events:none}
.service-file-plus{display:grid;place-items:center;flex:0 0 auto;width:28px;height:28px;border-radius:7px;background:rgba(214,166,44,.1);color:#d6a62c;font-size:15px}
.service-file-text{min-width:0;display:grid;gap:2px}
.service-file-text strong,.service-file-text span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.service-file-text strong{color:#dfe5e8;font-size:9px}
.service-file-text span{color:#74828b;font-size:8px}
.service-upload-btn{min-width:84px;height:50px;border:1px solid rgba(214,166,44,.35)!important;border-radius:8px!important;background:rgba(214,166,44,.1)!important;color:#d6a62c!important;font-size:8px!important;font-weight:800!important;letter-spacing:.09em;text-transform:uppercase}
.service-upload-btn:hover:not(:disabled){background:#d6a62c!important;color:#071019!important}
.service-upload-btn:disabled{opacity:.35}
.service-folder-note{margin:13px 0 0!important;font-size:9px!important}
@media(max-width:980px){.service-folder-grid{grid-template-columns:1fr}}
@media(max-width:560px){.service-upload-body{grid-template-columns:1fr}.service-upload-btn{width:100%;height:42px}}
`;

export default function ProjectDetailPage(){
 const params=useParams<{projectId:string}>(); const router=useRouter(); const projectId=decodeURIComponent(String(params.projectId||""));
 const [project,setProject]=useState<any>(null); const [employees,setEmployees]=useState<any[]>([]); const [assigned,setAssigned]=useState<string[]>([]); const [billing,setBilling]=useState<any>(null); const [drive,setDrive]=useState<any>(null); const [serviceFolders,setServiceFolders]=useState<ProjectServiceFolderInfo[]>([]); const [folderFiles,setFolderFiles]=useState<Record<string,File|null>>({}); const [uploadingFolder,setUploadingFolder]=useState(""); const [visits,setVisits]=useState<any[]>([]); const [documents,setDocuments]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [editing,setEditing]=useState(false); const [draft,setDraft]=useState<any>({}); const [savingTeam,setSavingTeam]=useState(false); const [savingProject,setSavingProject]=useState(false);
 async function load(){setLoading(true);setError("");try{const [p,allEmp,assignedEmp,bill,folder,services,sv,docs]=await Promise.all([landViewApi.getProject(projectId),landViewApi.getEmployees(),landViewApi.getProjectEmployees(projectId),landViewApi.getProjectBilling(projectId),landViewApi.getProjectDriveFolder(projectId),landViewApi.getProjectServiceFolders(projectId),landViewApi.getSiteVisits(projectId),landViewApi.getDocuments(projectId)]);setProject(p);setDraft(p);setEmployees(allEmp);setAssigned(assignedEmp.map((e:any)=>pick(e,["Employee_ID","Employee ID","EmployeeId"])).filter(Boolean));setBilling(bill);setDrive(folder);setServiceFolders(services.folders||[]);setVisits(sv);setDocuments(docs);}catch(e:any){setError(e?.message||"Could not load project.");}finally{setLoading(false)}}
 useEffect(()=>{if(projectId)load()},[projectId]);
 async function saveEdit(e:FormEvent){e.preventDefault();if(savingProject)return;setSavingProject(true);try{await landViewApi.updateProject(projectId,draft);setEditing(false);await load();}catch(e:any){setError(e?.message||"Update failed.")}finally{setSavingProject(false)}}
 async function saveTeam(){setSavingTeam(true);try{await landViewApi.updateProjectEmployees(projectId,assigned);await load();}catch(e:any){setError(e?.message||"Could not update team.");}finally{setSavingTeam(false)}}
 async function uploadToFolder(folderName:string){const file=folderFiles[folderName];if(!file)return;setUploadingFolder(folderName);setError("");try{await uploadProjectFile(projectId,folderName,file);setFolderFiles(v=>({...v,[folderName]:null}));await load();}catch(e:any){setError(e?.message||"Upload failed.");}finally{setUploadingFolder("")}}
 async function remove(){if(!window.confirm(`Delete ${projectId}? This deletes the project row.`))return;try{await landViewApi.deleteProject(projectId);router.push("/admin/projects");}catch(e:any){setError(e?.message||"Delete failed.")}}
 if(loading)return <LoadingState label="Loading project..."/>; if(error&&!project)return <ErrorState message={error} onRetry={load}/>;
 const title=pick(project,["Project_Name","Project Name","Name","Project_Type","Project Type"],projectId); const folderMap=new Map(serviceFolders.map(folder=>[folder.name,folder]));
 return <><style dangerouslySetInnerHTML={{__html:folderCss}}/>
  <PageHeader eyebrow={projectId} title={title} description={`${pick(project,["Client_Name","Client Name","Client"],"No client")} · ${pick(project,["Location","Address"],"Location not set")}`} action={<div className="button-row"><button className="btn btn-light" onClick={()=>setEditing(v=>!v)}>{editing?"Close edit":"Edit project"}</button>{drive?.url&&<a className="btn btn-dark" href={drive.url} target="_blank" rel="noreferrer">Drive folder ↗</a>}</div>}/>
  {error&&<div className="notice error"><strong>Notice</strong><span>{error}</span></div>}
  <div className="project-detail-grid"><section className="card project-summary"><div className="section-title"><div><span>PROJECT PROFILE</span><h2>Overview</h2></div><StatusBadge value={pick(project,["Status","status","Active"],"Active")}/></div><div className="detail-list"><div><span>Client</span><strong>{pick(project,["Client_Name","Client Name"],"—")}</strong></div><div><span>Phone</span><strong>{pick(project,["Phone_Number","Phone Number","Phone"],"—")}</strong></div><div><span>Type</span><strong>{pick(project,["Project_Type","Project Type"],"—")}</strong></div><div><span>Start date</span><strong>{formatDate(project.Start_Date||project["Start Date"])}</strong></div><div><span>Public website</span><strong>{String(pick(project,["Public_Display","Public Display"],"FALSE")).toUpperCase()==="TRUE"?"Visible":"Hidden"}</strong></div></div></section><section className="card card-dark finance-mini"><div className="card-kicker">PROJECT FINANCE</div><div className="finance-number"><Money value={billing?.due||0}/></div><p>Outstanding balance</p><div className="detail-list dark-list"><div><span>Total billed</span><strong><Money value={billing?.totalBill||0}/></strong></div><div><span>Total paid</span><strong><Money value={billing?.totalPaid||0}/></strong></div></div><Link href="/admin/finance">Manage finance →</Link></section></div>
  {editing&&<form className="card form-card compact" onSubmit={saveEdit}><div className="section-title"><div><span>EDIT</span><h2>Project details</h2></div></div><div className="form-grid">{[['Project_Name','PROJECT NAME'],['Client_Name','CLIENT NAME'],['Phone_Number','PHONE'],['Project_Type','PROJECT TYPE'],['Location','LOCATION'],['Design_Bill','DESIGN BILL'],['Status','STATUS'],['Start_Date','START DATE']].map(([key,label])=><Field key={key} label={label}><input type={key==='Start_Date'?'date':'text'} value={String(draft?.[key]??'')} onChange={e=>setDraft((v:any)=>({...v,[key]:e.target.value}))}/></Field>)}</div>
   <div className="form-section service-folder-panel"><div><span>FILES</span><h2>Project service folders</h2><p>Choose a file and upload it directly to its project folder in Google Drive. Images in 3D Design - Exterior are used automatically on the public website; name the main image front.jpeg.</p></div><div><div className="service-folder-grid">{PROJECT_SERVICE_FOLDERS.map((folderName,index)=>{const folder=folderMap.get(folderName);const selected=folderFiles[folderName];return <div className="card service-folder-card" key={folderName}><div className="service-folder-head"><span className="service-folder-number">{String(index+1).padStart(2,'0')}</span><strong className="service-folder-name">{folderName}</strong>{folder?.url&&<a className="service-folder-open" href={folder.url} target="_blank" rel="noreferrer">Open ↗</a>}</div><div className="service-upload-body"><label className="service-file-picker"><input type="file" onChange={e=>setFolderFiles(v=>({...v,[folderName]:e.target.files?.[0]||null}))}/><span className="service-file-plus">＋</span><span className="service-file-text"><strong>{selected?selected.name:"Choose a file"}</strong><span>{selected?`${(selected.size/1024/1024).toFixed(2)} MB`:"Browse from your device"}</span></span></label><button type="button" className="btn service-upload-btn" disabled={!selected||uploadingFolder===folderName} onClick={()=>uploadToFolder(folderName)}>{uploadingFolder===folderName?"Uploading…":"Upload"}</button></div></div>})}</div><p className="muted service-folder-note">App uploads: maximum 3 MB per file. For larger CAD drawings, renders or survey files, use the folder’s Open button.</p></div></div>
   <div className="form-section"><div><span>PUBLIC</span><h2>Website portfolio</h2><p>Project images are read automatically from the 3D Design - Exterior folder. No cover or gallery URLs are required.</p></div><div className="form-grid"><Field label="SHOW ON WEBSITE"><select value={String(draft?.Public_Display??'FALSE')} onChange={e=>setDraft((v:any)=>({...v,Public_Display:e.target.value}))}><option value="FALSE">No</option><option value="TRUE">Yes</option></select></Field><Field label="PUBLIC PROJECT TITLE"><input value={String(draft?.Public_Project_Title??'')} onChange={e=>setDraft((v:any)=>({...v,Public_Project_Title:e.target.value}))}/></Field><Field label="CATEGORY"><input value={String(draft?.Project_Category??'')} onChange={e=>setDraft((v:any)=>({...v,Project_Category:e.target.value}))}/></Field><Field label="PROJECT AREA"><input value={String(draft?.Project_Area??'')} onChange={e=>setDraft((v:any)=>({...v,Project_Area:e.target.value}))}/></Field><Field label="NUMBER OF STORIES"><input value={String(draft?.Number_of_Stories??'')} onChange={e=>setDraft((v:any)=>({...v,Number_of_Stories:e.target.value}))}/></Field><Field label="COMPLETION YEAR"><input value={String(draft?.Completion_Year??'')} onChange={e=>setDraft((v:any)=>({...v,Completion_Year:e.target.value}))}/></Field><Field label="DISPLAY ORDER"><input type="number" value={String(draft?.Public_Display_Order??'')} onChange={e=>setDraft((v:any)=>({...v,Public_Display_Order:e.target.value}))}/></Field><Field label="SERVICES" hint="Separate with • or new lines"><textarea rows={4} value={String(draft?.Public_Services??'')} onChange={e=>setDraft((v:any)=>({...v,Public_Services:e.target.value}))}/></Field><Field label="PUBLIC DESCRIPTION"><textarea rows={5} value={String(draft?.Public_Description??'')} onChange={e=>setDraft((v:any)=>({...v,Public_Description:e.target.value}))}/></Field></div></div><div className="form-actions"><button type="button" onClick={remove} className="btn btn-danger">Delete project</button><button className="btn btn-dark" disabled={savingProject}>{savingProject?"Saving...":"Save changes"}</button></div></form>}
  <div className="two-col"><section className="card"><div className="section-title"><div><span>TEAM</span><h2>Assigned employees</h2></div><button className="btn btn-small" disabled={savingTeam} onClick={saveTeam}>{savingTeam?"Saving...":"Save team"}</button></div><div className="check-list">{employees.length?employees.map((e:any)=>{const id=pick(e,["Employee_ID","Employee ID","EmployeeId"]);return <label key={id}><input type="checkbox" checked={assigned.includes(id)} onChange={ev=>setAssigned(v=>ev.target.checked?[...v,id]:v.filter(x=>x!==id))}/><span><strong>{pick(e,["Employee_Name","Employee Name","Name"],id)}</strong><small>{pick(e,["Position","Department"],"Team member")}</small></span></label>}):<p className="muted">No employees available.</p>}</div></section><section className="card"><div className="section-title"><div><span>PROJECT RECORDS</span><h2>Activity</h2></div></div><div className="detail-list"><div><span>Documents</span><strong>{documents.length}</strong></div><div><span>Site visits</span><strong>{visits.length}</strong></div><div><span>Bills</span><strong>{billing?.bills?.length||0}</strong></div><div><span>Payments</span><strong>{billing?.payments?.length||0}</strong></div></div></section></div>
 </>;
}
