"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { getProposalPermissions, listProposals, type ProposalRecord } from "@/lib/proposal-api";

const money=(v:unknown)=>new Intl.NumberFormat("en-BD",{style:"currency",currency:"BDT",maximumFractionDigits:2}).format(Number(v)||0);
const dateText=(v?:string)=>{if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"})};

export default function ProposalsPage(){
  const [rows,setRows]=useState<ProposalRecord[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("All"),[canCreate,setCanCreate]=useState(false);
  async function load(){setLoading(true);setError("");try{const [data,access]=await Promise.all([listProposals(),getProposalPermissions()]);setRows(data||[]);const role=String(access?.role||"").toLowerCase();setCanCreate(role==="admin"||role==="manager"||Boolean(access?.permissions?.["proposals.create"]))}catch(e){setError(e instanceof Error?e.message:"Could not load proposals.")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  const statuses=useMemo(()=>Array.from(new Set(rows.map(r=>String(r.Status||"Draft")).filter(Boolean))).sort(),[rows]);
  const filtered=useMemo(()=>{const term=query.trim().toLowerCase();return rows.filter(r=>(status==="All"||String(r.Status||"Draft")===status)&&[r.Proposal_ID,r.Client_Name,r.Phone,r.Project_Title,r.Project_Location,r.Assigned_To,r.Status].join(" ").toLowerCase().includes(term))},[rows,query,status]);
  const total=filtered.reduce((s,r)=>s+Number(r.Net_Amount||0),0);
  const active=rows.filter(r=>!["Accepted","Rejected","Expired","Converted"].includes(String(r.Status||"Draft"))).length;
  return <div className="proposal-register"><style>{`
    .proposal-register{color:#eef2f5}.pr-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-end;margin-bottom:18px}.pr-head h1{font-size:36px;margin:5px 0 0}.pr-head p{margin:6px 0 0;color:#8e9ba5;font-size:11px;line-height:1.6}.pr-actions{display:flex;gap:8px}.pr-btn{border:1px solid #394650;border-radius:8px;background:#17222b;color:#eef2f5;padding:10px 13px;text-decoration:none;font-size:10px;font-weight:900;cursor:pointer}.pr-btn.primary{background:#d61f26;border-color:#d61f26}.pr-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:14px}.pr-metric{padding:15px;border:1px solid #303b44;border-radius:11px;background:#101820}.pr-metric span{display:block;color:#7f8c96;font-size:9px;font-weight:900;text-transform:uppercase}.pr-metric strong{display:block;margin-top:7px;font-size:23px}.pr-tools{display:flex;gap:8px;margin-bottom:12px}.pr-tools input,.pr-tools select{border:1px solid #35414b;border-radius:8px;background:#0b1218;color:#eef2f5;padding:10px 11px;font-size:10px}.pr-tools input{flex:1}.pr-panel{border:1px solid #303b44;border-radius:12px;background:#101820;overflow:hidden}.pr-table-wrap{overflow:auto}.pr-table{width:100%;min-width:1050px;border-collapse:collapse}.pr-table th{padding:11px 12px;background:#17222b;color:#83919b;text-align:left;font-size:9px;text-transform:uppercase;border-bottom:2px solid #d61f26}.pr-table td{padding:12px;border-bottom:1px solid #27323b;font-size:10px;vertical-align:top}.pr-table tr:hover td{background:#121d25}.pr-id{color:#ff7d75;font-weight:900;text-decoration:none}.pr-name{font-weight:900}.pr-sub{display:block;margin-top:4px;color:#77858f;font-size:9px}.pr-status{display:inline-flex;padding:5px 8px;border-radius:999px;background:#25313a;color:#c5ced4;font-size:8px;font-weight:900}.pr-status.Sent,.pr-status.Negotiating{background:#3b321c;color:#f3d582}.pr-status.Accepted,.pr-status.Converted{background:#153a29;color:#9ee5b9}.pr-status.Rejected,.pr-status.Expired{background:#3c2022;color:#ffaaa6}.pr-empty{padding:30px;text-align:center;color:#7f8b95}.pr-error{padding:12px 14px;border:1px solid #74373b;border-radius:8px;background:#351c1e;color:#ffb1ad;margin-bottom:12px}@media(max-width:760px){.pr-head{align-items:flex-start;flex-direction:column}.pr-metrics{grid-template-columns:1fr}.pr-tools{flex-direction:column}}
  `}</style>
  <header className="pr-head"><div><small style={{color:"#ef6c66",fontWeight:900,letterSpacing:".14em"}}>LAND VIEW / SALES PIPELINE</small><h1>Proposals</h1><p>Prospective clients stay separate from live projects and accounting until they accept the proposal.</p></div><div className="pr-actions"><button className="pr-btn" onClick={()=>void load()} disabled={loading}>↻ Refresh</button>{canCreate&&<Link className="pr-btn primary" href="/admin/proposals/new">+ Add Client</Link>}</div></header>
  {error&&<div className="pr-error">{error}</div>}
  <section className="pr-metrics"><div className="pr-metric"><span>Total proposals</span><strong>{rows.length}</strong></div><div className="pr-metric"><span>Active pipeline</span><strong>{active}</strong></div><div className="pr-metric"><span>Filtered value</span><strong>{money(total)}</strong></div></section>
  <div className="pr-tools"><input type="search" placeholder="Find proposal, client, phone, project or employee…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div>
  <section className="pr-panel"><div className="pr-table-wrap"><table className="pr-table"><thead><tr><th>Proposal</th><th>Prospective client</th><th>Project</th><th>Assigned</th><th>Net proposal</th><th>Status</th><th>Updated</th></tr></thead><tbody>{filtered.map(row=><tr key={row.Proposal_ID}><td><Link className="pr-id" href={`/admin/proposals/${encodeURIComponent(String(row.Proposal_ID||""))}`}>{row.Proposal_ID}</Link><span className="pr-sub">{row.Prospect_ID||""}</span></td><td><span className="pr-name">{row.Client_Name}</span><span className="pr-sub">{row.Phone}{row.Email?` · ${row.Email}`:""}</span></td><td><span className="pr-name">{row.Project_Title||row.Project_Type||"Proposal services"}</span><span className="pr-sub">{row.Project_Location||row.Address||"—"}</span></td><td>{row.Assigned_To||"—"}</td><td><strong>{money(row.Net_Amount)}</strong></td><td><span className={`pr-status ${String(row.Status||"Draft")}`}>{row.Status||"Draft"}</span></td><td>{dateText(row.Updated_At||row.Created_At)}</td></tr>)}{!filtered.length&&!loading&&<tr><td colSpan={7}><div className="pr-empty">No proposals match this view.</div></td></tr>}{loading&&<tr><td colSpan={7}><div className="pr-empty">Loading proposals…</div></td></tr>}</tbody></table></div></section>
  </div>
}
