from pathlib import Path

p=Path('components/certificate-document.tsx')
s=p.read_text()
s=s.replace('.lv-cert .lv-cert-signatures{position:relative;display:flex;justify-content:center;align-items:center;margin-top:30px;break-inside:avoid;text-align:center}\n.lv-cert .lv-cert-verify{display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;font-size:9px;min-width:130px}\n.lv-cert .lv-cert-verify img{display:block;width:82px;height:82px;padding:0;background:#fff;object-fit:contain;margin:0 auto 6px}\n.lv-cert .lv-cert-verify strong{display:block;font-size:10px;font-weight:800}.lv-cert .lv-cert-verify span{display:block;color:#666!important;line-height:1.25;margin-top:2px}', '.lv-cert .lv-cert-signatures{position:relative;display:flex;justify-content:center;align-items:center;margin-top:28px;break-inside:avoid;text-align:center}\n.lv-cert .lv-cert-verify{display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;font-size:10px;min-width:150px}\n.lv-cert .lv-cert-verify img{display:block;width:96px;height:96px;padding:5px;background:#fff;object-fit:contain;margin:0 auto 7px;image-rendering:auto}\n.lv-cert .lv-cert-verify strong{display:block;font-size:11px;font-weight:800}.lv-cert .lv-cert-verify span{display:block;color:#555!important;line-height:1.25;margin-top:2px;font-size:9px}')
s=s.replace('.lv-cert .lv-cert-footer{position:absolute;bottom:0;left:0;right:0;height:114px;display:grid;grid-template-columns:1fr 1.2fr 1.2fr;gap:18px;align-items:end;padding:0 45px 17px;color:#fff!important;background:linear-gradient(165deg,#ba1018 0 26%,#272727 26% 42%,#111 42%);clip-path:polygon(0 0,43% 48%,100% 0,100% 100%,0 100%);font-size:9px}\n.lv-cert .lv-cert-footer small{display:block;font-size:5.7px;letter-spacing:.6px;color:#ccc!important;margin-top:5px}', '.lv-cert .lv-cert-footer{position:absolute;bottom:0;left:0;right:0;height:114px;display:grid;grid-template-columns:1fr 1.2fr 1.2fr;gap:22px;align-items:end;padding:0 45px 18px;color:#fff!important;background:linear-gradient(165deg,#ba1018 0 26%,#272727 26% 42%,#111 42%);clip-path:polygon(0 0,43% 48%,100% 0,100% 100%,0 100%);font-size:11px;font-weight:600}\n.lv-cert .lv-cert-footer small{display:block;font-size:7px;line-height:1.25;letter-spacing:.45px;color:#ddd!important;margin-top:4px;font-weight:500}')
s=s.replace('@media print{@page{size:A4 portrait;margin:0}html,body{margin:0!important;padding:0!important;background:#fff!important}.lv-cert-scroll{overflow:visible}.lv-cert{width:210mm!important;min-height:297mm!important;margin:0!important;box-shadow:none!important;-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}}', '@media print{@page{size:A4 portrait;margin:0}html,body{margin:0!important;padding:0!important;background:#fff!important}.lv-cert-scroll{overflow:visible}.lv-cert{width:210mm!important;min-height:297mm!important;margin:0!important;box-shadow:none!important;-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}.lv-cert .lv-cert-verify img{width:25mm!important;height:25mm!important;padding:1.2mm!important}.lv-cert .lv-cert-footer{font-size:11px!important}.lv-cert .lv-cert-footer small{font-size:7px!important}}')
p.write_text(s)

p=Path('app/api/certificates/route.ts')
s=p.read_text()
s=s.replace('function certificateUrls(request: NextRequest, token: string) {\n  if (!token) return { verificationUrl: "", qrUrl: "" };\n  const origin = `${request.nextUrl.protocol}//${request.nextUrl.host}`;\n  const verificationUrl = `${origin}/certificate/verify/${encodeURIComponent(token)}`;\n  const qrUrl = `${origin}/api/billing-verification/qr?data=${encodeURIComponent(verificationUrl)}`;\n  return { verificationUrl, qrUrl };\n}', 'function certificateUrls(request: NextRequest, token: string, certificateId = "") {\n  if (!token) return { verificationUrl: "", qrUrl: "" };\n  const origin = `${request.nextUrl.protocol}//${request.nextUrl.host}`;\n  const verificationUrl = `${origin}/certificate/verify/${encodeURIComponent(token)}`;\n  // Keep the printed QR compact like invoice QRs. The short certificate-ID URL\n  // is resolved against the live registry; the full signed link remains available.\n  const qrTarget = certificateId ? `${origin}/certificate/verify/${encodeURIComponent(certificateId)}` : verificationUrl;\n  const qrUrl = `${origin}/api/billing-verification/qr?data=${encodeURIComponent(qrTarget)}`;\n  return { verificationUrl, qrUrl };\n}')
s=s.replace('...certificateUrls(request, signed),', '...certificateUrls(request, signed, clean(item?.certificateId || item?.Certificate_ID, 60)),')
s=s.replace('const urls = certificateUrls(request, signedToken);', 'const urls = certificateUrls(request, signedToken, certificateId);')
p.write_text(s)

p=Path('app/certificate/verify/[token]/page.tsx')
s=p.read_text()
s=s.replace('  deletedReason?: string;\n};', '  deletedReason?: string;\n  token?: string; Token?: string; type?: string; Type?: string; name?: string; Name?: string; address?: string; Address?: string; position?: string; Position?: string; subject?: string; Subject?: string; reference?: string; Reference?: string; description?: string; Description?: string; issuedAt?: string; Issued_At?: string; expiresAt?: string; Expires_At?: string; fatherName?: string; Father_Name?: string; motherName?: string; Mother_Name?: string; nidNo?: string; NID_No?: string;\n};')
old='''  const { token } = await params;\n  const certificate = verifyCertificate(decodeURIComponent(token || ""));\n\n  if (!certificate) {'''
new='''  const { token } = await params;\n  const decoded = decodeURIComponent(token || "");\n  const shortId = /^LVC-(?:EMP|PRJ|BLD)-/i.test(decoded) ? decoded.toUpperCase() : "";\n  const shortRegistry = shortId ? await registryStatus(shortId) : null;\n  const row: any = shortRegistry?.certificate || {};\n  const storedToken = String(row.token || row.Token || "").trim();\n  let certificate: any = storedToken ? verifyCertificate(storedToken) : verifyCertificate(decoded);\n  if (!certificate && shortRegistry?.found) {\n    certificate = {\n      id: shortId, t: String(row.type || row.Type || "project").toLowerCase(),\n      n: row.name || row.Name || "LAND VIEW certificate holder", a: row.address || row.Address || "",\n      p: row.position || row.Position || "", s: row.subject || row.Subject || "", r: row.reference || row.Reference || "",\n      d: row.description || row.Description || "", i: row.issuedAt || row.Issued_At || "", x: row.expiresAt || row.Expires_At || "",\n      f: row.fatherName || row.Father_Name || "", m: row.motherName || row.Mother_Name || "", nid: row.nidNo || row.NID_No || ""\n    };\n  }\n\n  if (!certificate) {'''
if old not in s: raise SystemExit('verify target not found')
s=s.replace(old,new)
s=s.replace('  const registry = await registryStatus(certificate.id);', '  const registry = shortRegistry || await registryStatus(certificate.id);')
p.write_text(s)
print('Improved certificate print legibility and compact QR target.')
