"use client";

import Link from "next/link";
import { useRef, useState, type FormEvent } from "react";
import { landViewApi, type FinanceSheetData } from "@/lib/api";
import { buildSheetInvoices, invoiceTabs, normalizeFileId, type SheetInvoices } from "@/lib/sheet-invoices";
import styles from "./invoice.module.css";

const money = (value: number) => new Intl.NumberFormat("en-BD", { style: "currency", currency: "BDT", maximumFractionDigits: 0 }).format(value);
function statementDate(){return new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Dhaka",day:"2-digit",month:"short",year:"numeric"}).format(new Date());}
async function loadFinanceTabs(){const results:FinanceSheetData[]=new Array(invoiceTabs.length);let cursor=0;async function worker(){while(cursor<invoiceTabs.length){const index=cursor++;results[index]=await landViewApi.getFinanceSheet(invoiceTabs[index]);}}await Promise.all(Array.from({length:3},()=>worker()));return results;}

export default function ProjectBillingPage(){
  const [fileId,setFileId]=useState("");const [result,setResult]=useState<SheetInvoices|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [generated,setGenerated]=useState("");const [verificationUrl,setVerificationUrl]=useState("");const [verificationError,setVerificationError]=useState("");const request=useRef(0);

  async function createVerification(billing:SheetInvoices,version:number){try{const response=await fetch("/api/billing-verification",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fileId:billing.id,clientName:billing.client.name,projectType:billing.client.type,totals:billing.totals,categories:billing.invoices.map(c=>({name:c.name,gross:c.gross,discount:c.discount,paid:c.paid,due:c.due}))})});const json=await response.json();if(!response.ok||!json?.success||!json?.url)throw new Error(json?.error||"Could not create verification link.");if(request.current===version)setVerificationUrl(String(json.url));}catch(err){if(request.current===version)setVerificationError(err instanceof Error?err.message:"Could not create verification link.");}}

  async function load(event:FormEvent){event.preventDefault();const id=normalizeFileId(fileId);if(!id)return setError("Enter a File ID such as 209 or LV-209.");const version=++request.current;setBusy(true);setError("");setResult(null);setVerificationUrl("");setVerificationError("");try{const billing=buildSheetInvoices(await loadFinanceTabs(),id);if(version===request.current){setResult(billing);setGenerated(statementDate());void createVerification(billing,version);}}catch(err){if(version===request.current)setError(err instanceof Error?err.message:"Could not load project billing.");}finally{if(version===request.current)setBusy(false);}}

  const qrUrl=verificationUrl?`/api/billing-verification/qr?data=${encodeURIComponent(verificationUrl)}`:"";
  const categoryLabel=(name:string)=>name==="Design"?"Engineering":name;

  const renderTable=(category:SheetInvoices["invoices"][number],type:"bill"|"deposit")=>{
    if(type==="bill"){
      if(!category.items.length)return <p className={styles.empty}>No bill records.</p>;
      return <div className={styles.tableWrap}><table><thead><tr><th>SL.</th><th>Description</th><th>Rate</th><th>Qty.</th><th>Amount</th></tr></thead><tbody>{category.items.map((item,index)=><tr key={index}><td>{index+1}</td><td>{item.service||"—"}</td><td>{item.price||"—"}</td><td>{item.quantity||"—"}</td><td>{money(item.amount)}</td></tr>)}</tbody><tfoot><tr className={styles.tableTotal}><td colSpan={4}>Total {categoryLabel(category.name)} Bill</td><td>{money(category.gross)}</td></tr></tfoot></table></div>;
    }
    if(!category.payments.length)return <p className={styles.empty}>No deposit records.</p>;
    return <div className={styles.tableWrap}><table><thead><tr><th>SL.</th><th>Date</th><th>Payment Details</th><th colSpan={2}>Amount</th></tr></thead><tbody>{category.payments.map((payment,index)=><tr key={index}><td>{index+1}</td><td>{payment.date||"—"}</td><td>{payment.details||"—"}</td><td colSpan={2}>{money(payment.amount)}</td></tr>)}</tbody><tfoot><tr className={styles.tableTotal}><td colSpan={4}>Total {categoryLabel(category.name)} Deposit</td><td>{money(category.paid)}</td></tr></tfoot></table></div>;
  };

  const PrintHeader=({page,title}:{page:number;title:string})=><><header className={styles.sheetHeader}><div className={styles.sheetBrand}><strong>LAND <span>VIEW</span></strong><small>ENGINEERS AND ARCHITECTS</small><em>Building a safer tomorrow</em></div><div className={styles.sheetContact}><span>●&nbsp; Feni Sadar, Feni, Bangladesh</span><span>●&nbsp; +88 01902 500 400</span><span>●&nbsp; landviewcivil@gmail.com</span><span>●&nbsp; www.landview.com.bd</span></div><div className={styles.sheetTitle}><small>Page {page} of 3</small><b>Project Billing Statement</b><strong>{title}</strong></div></header><section className={styles.sheetClient}><div><span>Client Name</span><strong>{result?.client.name||"—"}</strong><span>Address</span><strong>{result?.client.address||"—"}</strong><span>Phone</span><strong>{result?.client.phone||"—"}</strong></div><div><span>File ID</span><strong>{result?.id||"—"}</strong><span>Project Type</span><strong>{result?.client.type||"—"}</strong><span>Floor / Story</span><strong>{result?.client.floor||"—"}</strong></div><div><span>Issue Date</span><strong>{generated||"—"}</strong><span>Reference No.</span><strong>{result?`${result.id}-01`:"—"}</strong><span>Status</span><strong className={styles.sheetStatus}>{result&&result.totals.due>0?"Partial Payment":"Full Paid"}</strong></div></section></>;

  return <div className={styles.workspace}>
    <div className={styles.header}><div><Link href="/admin/finance">← Finance</Link><span className={styles.eyebrow}>LAND VIEW / ACCOUNTS</span><h1>Project Billing Lookup</h1><p>Enter a File ID to pull every bill and deposit and calculate the live balance.</p></div>{result&&<button className={styles.printButton} type="button" onClick={()=>window.print()}>Print / Save PDF</button>}</div>
    <form className={styles.lookup} onSubmit={load}><label htmlFor="billing-file">File ID</label><input id="billing-file" placeholder="209 or LV-209" value={fileId} onChange={e=>{setFileId(e.target.value);setResult(null);setError("");setVerificationUrl("");setVerificationError("");request.current++;setBusy(false);}} required autoComplete="off"/><button disabled={busy}>{busy?"Loading…":"View billing"}</button></form>
    {error&&<div className={styles.error} role="alert">{error}</div>}{busy&&<div className={styles.loading} role="status">Pulling bill and deposit records…</div>}

    {result&&<><main className={styles.report}><header className={styles.printHeader}><div><strong>LAND <span>VIEW</span></strong><small>Engineers and Architects</small></div><div><h2>PROJECT BILLING STATEMENT</h2><p>Generated {generated}</p></div></header><section className={styles.projectCard}><div><span>FILE ID</span><strong>{result.id}</strong></div><div><span>CLIENT</span><strong>{result.client.name||"—"}</strong><small>{result.client.phone||"—"}</small></div><div><span>PROJECT TYPE</span><strong>{result.client.type||"—"}</strong><small>{result.client.floor||"—"}</small></div><div className={styles.totalDueCard}><span>TOTAL DUE</span><strong>{money(result.totals.due)}</strong></div></section><section className={styles.categoryGrid}>{result.invoices.map(c=><article className={styles.category} key={c.name}><div className={styles.categoryHeader}><div><span>{c.name.toUpperCase()}</span><h2>{categoryLabel(c.name)} Billing</h2></div><div className={c.due>0?styles.dueBadge:styles.paidBadge}>{c.due>0?"DUE":"PAID"}</div></div><div className={styles.metrics}><div><span>Bill</span><strong>{money(c.gross)}</strong></div><div><span>Discount</span><strong>{money(c.discount)}</strong></div><div><span>Deposited</span><strong>{money(c.paid)}</strong></div><div><span>Due</span><strong>{money(c.due)}</strong></div></div><div className={styles.split}><section><h3>{categoryLabel(c.name)} Bill</h3>{renderTable(c,"bill")}</section><section><h3>{categoryLabel(c.name)} Deposit</h3>{renderTable(c,"deposit")}</section></div></article>)}</section><section className={styles.grandSummary}><div><span>Total Bill</span><strong>{money(result.totals.gross)}</strong></div><div><span>Total Discount</span><strong>{money(result.totals.discount)}</strong></div><div><span>Total Deposited</span><strong>{money(result.totals.paid)}</strong></div><div className={styles.grandDue}><span>Grand Total Due</span><strong>{money(result.totals.due)}</strong></div></section></main>

    <section className={styles.printSheets}>
      {result.invoices.slice(0,2).map((category,index)=><article className={styles.printPage} key={category.name}><PrintHeader page={index+1} title={`${categoryLabel(category.name)} Bill`}/><div className={styles.sheetBody}><section className={styles.sheetMain}><h2>{categoryLabel(category.name).toUpperCase()} <span>BILL</span></h2><p className={styles.sheetSubtitle}>{category.name==="Design"?"Design, Drawing and Related Engineering Services":"Site Supervision and Related Services"}</p>{renderTable(category,"bill")}<h2 className={styles.depositHeading}>{categoryLabel(category.name).toUpperCase()} <span>DEPOSIT / PAYMENTS</span></h2>{renderTable(category,"deposit")}</section><aside className={styles.sheetSummary}><h3>{categoryLabel(category.name).toUpperCase()} SUMMARY</h3><div><span>Total {categoryLabel(category.name)} Bill</span><strong>{money(category.gross)}</strong></div><div><span>Total Deposit</span><strong>{money(category.paid)}</strong></div><div><span>Discount</span><strong>{money(category.discount)}</strong></div><div className={styles.sheetDue}><span>{categoryLabel(category.name)} Due</span><strong>{money(category.due)}</strong></div><div className={styles.sheetNote}>ⓘ<span>This page contains only<br/>{categoryLabel(category.name)} Bill and related payments.</span></div></aside></div><footer className={styles.sheetFooter}><strong>LAND VIEW <span>— Engineers and Architects</span></strong><span>A SAFER BUILT ENVIRONMENT FOR A BETTER TOMORROW</span></footer></article>)}

      <article className={styles.printPage}><PrintHeader page={3} title="Others Bill & Summary"/><div className={styles.sheetBody}><section className={styles.sheetMain}><h2>OTHERS <span>BILL</span></h2><p className={styles.sheetSubtitle}>Additional Services and Related Charges</p>{renderTable(result.invoices[2],"bill")}<h2 className={styles.depositHeading}>OTHERS <span>DEPOSIT / PAYMENTS</span></h2>{renderTable(result.invoices[2],"deposit")}</section><aside className={styles.sheetSummary}><h3>OTHERS SUMMARY</h3><div><span>Total Others Bill</span><strong>{money(result.invoices[2].gross)}</strong></div><div><span>Total Deposit</span><strong>{money(result.invoices[2].paid)}</strong></div><div><span>Discount</span><strong>{money(result.invoices[2].discount)}</strong></div><div className={styles.sheetDue}><span>Others Due</span><strong>{money(result.invoices[2].due)}</strong></div><h3 className={styles.grandHeading}>GRAND SUMMARY</h3>{result.invoices.map(c=><div key={c.name}><span>{categoryLabel(c.name)} Due</span><strong>{money(c.due)}</strong></div>)}<div className={styles.sheetGrandDue}><span>GRAND TOTAL DUE</span><strong>{money(result.totals.due)}</strong></div></aside></div><div className={styles.sheetBottom}><div className={styles.sheetThanks}>Thank you for your trust in LAND VIEW.<br/>For any query, please contact us.</div><div className={styles.sheetSignature}><span>Authorized Signature</span><strong>LAND VIEW</strong><small>Engineers and Architects</small></div><div className={styles.sheetQr}>{qrUrl?<img src={qrUrl} alt={`QR code to verify ${result.id}`} width={220} height={220}/>:<div className={styles.qrPlaceholder}>{verificationError||"Preparing QR…"}</div>}<div><strong>Scan this QR code</strong><span>to verify this billing statement</span><b>File ID&nbsp; : &nbsp;{result.id}</b><small>Verify at: app.landview.com.bd/verify</small></div></div></div><footer className={styles.sheetFooter}><strong>LAND VIEW <span>— Engineers and Architects</span></strong><span>A SAFER BUILT ENVIRONMENT FOR A BETTER TOMORROW</span></footer></article>
    </section></>}
  </div>;
}
