"use client";

import { useEffect, useMemo, useState } from "react";
import { landViewApi } from "@/lib/api";

type Row=Record<string,any>;
const accountingUrl="https://docs.google.com/spreadsheets/d/1E1hCMKn3fGl7LUov1FS60IJNVnZTJUlf6CCO4pFMQw4/edit";
function t(v:any){return String(v??"").trim()}
function money(v:any){const n=Number(String(v??0).replace(/,/g,""));return Number.isFinite(n)?`৳${n.toLocaleString("en-BD")}`:"৳0"}
function status(r:Row){return t(r.Status||r.status)||"Pending"}

export default function ExpensesPage(){
 const [rows,setRows]=useState<Row[]>([]),[session,setSession]=useState<any>(null),[perms,setPerms]=useState<Row[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const [e,s,p]=await Promise.all([landViewApi.getErpRecords("expenses"),landViewApi.getSession(),landViewApi.getPermissions().catch(()=>[])]);setRows(e||[]);setSession(s);setPerms(p||[])}catch(e:any){setError(e?.message||"Could not load expenses.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const role=t(session?.user?.role||session?.user?.Role).toLowerCase(); const userId=t(session?.user?.userId||session?.user?.User_ID);
 const canApprove=role==="admin" || latest(perms,userId,"expenses.approve");
 const pending=useMemo(()=>rows.filter(r=>status(r).toLowerCase()==="pending"),[rows]);
 const approved=useMemo(()=>rows.filter(r=>status(r).toLowerCase()==="approved"),[rows]);
 const totals={pending:pending.reduce((s,r)=>s+Number(r.Amount||0),0),approved:approved.reduce((s,r)=>s+Number(r.Amount||0),0)};
 async function decide(r:Row,next:string){const id=t(r.Expense_ID||r["Expense ID"]);if(!id)return;setBusy(id);try{await landViewApi.updateErpRecord("expenses",id,{Status:next,Reviewed_By:userId,Reviewed_At:new Date().toISOString()});setRows(prev=>prev.map(x=>t(x.Expense_ID||x["Expense ID"])===id?{...x,Status:next,Reviewed_By:userId,Reviewed_At:new Date().toISOString()}:x));}catch(e:any){setError(e?.message||"Could not update expense.")}finally{setBusy("")}}
 return <div className="expense-page"><style>{`
 .expense-page{color:#eef2f5}.expense-head{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:20px}.expense-head h1{margin:5px 0 0;font-size:34px}.expense-head p{max-width:650px;color:#95a1ab;font-size:12px;line-height:1.6}.expense-head-actions{display:flex;flex-direction:column;align-items:flex-end;gap:9px}.ledger-link{display:inline-flex;align-items:center;justify-content:center;min-height:36px;padding:0 12px;border:1px solid #52606b;border-radius:8px;background:#17222b;color:#fff;text-decoration:none;font-size:10px;font-weight:800;white-space:nowrap}.ledger-note{max-width:340px;text-align:right;color:#71808b;font-size:9px;line-height:1.45}.expense-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:18px}.expense-stat{padding:16px;border:1px solid #33404a;border-radius:10px;background:#111a22}.expense-stat span{display:block;color:#87949e;font-size:10px}.expense-stat strong{display:block;margin-top:7px;font-size:25px}.expense-card{border:1px solid #33404a;border-radius:11px;background:#101820;overflow:hidden}.expense-row{display:grid;grid-template-columns:120px minmax(220px,1.5fr) 140px 130px 180px;gap:12px;align-items:center;padding:13px 15px;border-bottom:1px solid #29343d}.expense-row:last-child{border-bottom:0}.expense-row.head{background:#17222b;color:#84929d;font-size:10px;text-transform:uppercase;font-weight:800}.expense-row strong,.expense-row small{display:block}.expense-row small{margin-top:4px;color:#7f8c96}.badge{display:inline-flex;padding:5px 8px;border-radius:999px;background:#2d3740;font-size:10px}.badge.pending{background:#4b3b1b;color:#ffd77d}.badge.approved{background:#183c2b;color:#8be0ad}.badge.rejected{background:#452022;color:#ff9d9d}.actions{display:flex;gap:7px}.actions button{border:1px solid #49545e;background:#18232c;color:#fff;border-radius:7px;padding:7px 9px;font-size:10px;cursor:pointer}.actions .approve{border-color:#2d6a49;color:#8ee2ad}.actions .reject{border-color:#7d373a;color:#ff9e9e}.err{padding:11px 13px;margin-bottom:14px;background:#3b1d1e;border:1px solid #78373a;border-radius:8px;color:#ffb0b0}@media(max-width:900px){.expense-head{align-items:flex-start;flex-direction:column}.expense-head-actions{align-items:flex-start}.ledger-note{text-align:left}.expense-stats{grid-template-columns:1fr}.expense-card{overflow:auto}.expense-row{min-width:850px}}
 `}</style><div className="expense-head"><div><small>OFFICE OPERATIONS</small><h1>Day-to-day expenses</h1><p>Regular LAND VIEW office expenses stay separate from client billing. Staff submit them as Pending; the authorized approver can approve or reject them.</p></div><div className="expense-head-actions"><a className="ledger-link" href={accountingUrl} target="_blank" rel="noopener noreferrer">Open income & expense database ↗</a><span className="ledger-note">App payments and expense approvals are mirrored into the accounting ledger by the Apps Script finance sync.</span></div></div>{error&&<div className="err">{error}</div>}<div className="expense-stats"><div className="expense-stat"><span>PENDING APPROVAL</span><strong>{money(totals.pending)}</strong><small>{pending.length} expense(s)</small></div><div className="expense-stat"><span>APPROVED TOTAL</span><strong>{money(totals.approved)}</strong><small>{approved.length} approved</small></div><div className="expense-stat"><span>RECORDS</span><strong>{rows.length}</strong><small>{canApprove?"Approval access enabled":"View-only approval access"}</small></div></div>{loading?<div>Loading expenses…</div>:<div className="expense-card"><div className="expense-row head"><div>Date</div><div>Expense</div><div>Amount</div><div>Status</div><div>Decision</div></div>{[...rows].reverse().map((r,i)=>{const id=t(r.Expense_ID||r["Expense ID"])||String(i);const st=status(r);return <div className="expense-row" key={id}><div>{t(r.Expense_Date||r["Expense Date"])||"—"}</div><div><strong>{t(r.Description)||t(r.Category)||"Office expense"}</strong><small>{t(r.Category)}{r.Created_By?` · by ${t(r.Created_By)}`:""}{r.Project_ID?` · ${t(r.Project_ID)}`:""}</small></div><div><strong>{money(r.Amount)}</strong><small>{t(r.Payment_Method)}</small></div><div><span className={`badge ${st.toLowerCase()}`}>{st}</span></div><div>{canApprove&&st.toLowerCase()==="pending"?<div className="actions"><button className="approve" disabled={busy===id} onClick={()=>void decide(r,"Approved")}>Approve</button><button className="reject" disabled={busy===id} onClick={()=>void decide(r,"Rejected")}>Reject</button></div>:<small>{t(r.Reviewed_By)||"—"}</small>}</div></div>})}{!rows.length&&<div style={{padding:20,color:"#8996a0"}}>No office expenses recorded yet.</div>}</div>}</div>
}
function latest(rows:Row[],uid:string,key:string){const m=rows.filter(r=>t(r.User_ID||r["User ID"])===uid&&t(r.Permission)===key).sort((a,b)=>new Date(t(a.Created_At)||0).getTime()-new Date(t(b.Created_At)||0).getTime());const x=m[m.length-1];return !!x&&t(x.Status).toLowerCase()==="active"}
